### ISSUE TITLE
This package will trigger a very slow auto-completion of company-mode.

### ISSUE THREAD

**Issue by hongyi-zhao** [astoff/comint-mime#1] opened 2021-09-18 13:49 UTC
On Ubuntu 20.04.2 LTS, I test this package with the following configuration:
```emacs-lisp
(use-package comint-mime
  :straight (:host github :type git :repo "astoff/comint-mime"
             :files (:defaults "*.py" "*.sh"))
  :after elpy
  ;https://github.com/jwiegley/use-package#hooks
  ;https://github.com/astoff/comint-mime#usage
  ;https://mail.google.com/mail/u/0?ik=7b73d6af10&view=om&permmsgid=msg-a%3Ar-1233702610310931433
  :hook (
        ((shell-mode inferior-python-mode) . comint-mime-setup)
        )
  :config
  (when (executable-find "ipython3")
    (setq python-shell-interpreter "ipython3"
          python-shell-interpreter-args "--simple-prompt --classic"
          ;https://elpy.readthedocs.io/en/latest/ide.html#interpreter-setup
          ;python-shell-interpreter-args "-i --simple-prompt --classic --pprint"
          )))
```
I find that it will trigger a very slow auto-completion of company-mode.

Regards,
HZ

**Comment by astoff** [comment] 2021-09-18 16:24
Can you reproduce this on `emacs -Q`, with only Company and comint-mime loaded?

**Comment by hongyi-zhao** [comment] 2021-09-19 00:59
I tested with the script `~/.emacs.d/init.company-comint-mime` as shown below, but failed to reproduce the problem:
```emacs-lisp
#!/usr/bin/env bash
:;#https://www.reddit.com/r/emacs/comments/a7ubx5/an_interactive_executable_combined_bash_and_emacs/
:;#https://github.com/alphapapa/matrix-client.el/blob/d2ac55293c96d4c95971ed8e2a3f6f354565c5ed/matrix-client-standalone.el.sh#L64-L81
:;# emacs -Q --insert <(tail -n +$(grep -n -m 1 -x ";;Bootstrap straight" "$0" | egrep -o '^[[:digit:]]+') "$0"); exit
:;#https://github.com/hlissner/doom-emacs/blob/develop/bin/doom
:;#https://lists.gnu.org/archive/html/help-gnu-emacs/2021-08/msg00101.html
:;#https://groups.google.com/g/comp.unix.shell/c/krxzfCd_8qM/m/W2Lc5W-jCAAJ
:;#https://groups.google.com/g/comp.unix.shell/c/krxzfCd_8qM/m/ryoNs9AGCQAJ
:; emacs -Q --load $(realpath -e $0) -- "$@"; exit
:;# or  
:;# exec emacs -Q --load $(realpath -e $0) -- "$@"


;;Bootstrap straight
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)


(use-package company
    :ensure t
    :config
    (global-company-mode)
    (setq company-idle-delay 0)
    (setq company-minimum-prefix-length 2)
    (setq company-selection-wrap-around t)
    (setq company-show-numbers t)
    :bind (:map company-active-map
                ("C-n" . company-select-next)
                ("C-p" . company-select-previous)
                ("C-s" . company-filter-candidates)
                ("<tab>" . company-complete-selection))
    :bind (:map company-search-map
                ("C-n" . company-select-next)
                ("C-p" . company-select-previous)))
                
                
                
(use-package comint-mime
  :straight (:host github :type git :repo "astoff/comint-mime")
;  :after elpy
  ;https://github.com/jwiegley/use-package#hooks
  ;https://github.com/astoff/comint-mime#usage
  ;https://mail.google.com/mail/u/0?ik=7b73d6af10&view=om&permmsgid=msg-a%3Ar-1233702610310931433
  :hook (
        ((shell-mode inferior-python-mode) . comint-mime-setup)
        )
) 
```

**Comment by hongyi-zhao** [comment] 2021-09-19 04:27
I tried with some further testings. It seems that the problem sometimes appears, sometimes doesn't. I still don't understand the reason till now.

**Comment by astoff** [comment] 2021-09-19 08:12
Yes, there are lots of moving parts there.  But I suspect this has
nothing to do with comint-mime.  Note that the Python shell completion
table changed recently in Emacs's master branch.  I'd suggest checking
if that is the origin of the slowness you observed.

**Comment by hongyi-zhao** [comment] 2021-09-19 08:37
I use an exhaustive [word list](https://github.com/hongyi-zhao/english-wordlist/blob/master/american-english-exhaustive) for ispell and [company-ispell](https://github.com/company-mode/company-mode/blob/master/company-ispell.el), which is the suspected culprit for this problem. But I don't experience the same problem in [AUCTeX](https://www.gnu.org/software/auctex/), which puzzle me the most.

**Comment by astoff** [comment] 2022-02-13 14:44
Since this seems unrelated to comint-mime I'll close the issue.

**Closed by astoff** 2022-02-13 14:44 UTC
